apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SHALEV</title>
    </head>
    <body>
        <h1>Welcome to Azure AKS!</h1>
    </body>
    </html>
