apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-agic
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway # This annotation links to AGIC
    # Optional: If you want to force HTTPS redirection
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "{{ .Values.ingressHost }}" # <--- This is the placeholder for your dynamic domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service 
            port:
              number: 80
